"""
        adjective_one = input("Enter an adjective: ")
        feeling_one = input("Enter a feeling: ")
        noun_one = input("Enter a noun: ")
        place_one = input("Enter a place: ")
        adjective_two = input("Enter another adjective: ")
        animal_one = input("Enter a type of animal: ")
        noun_two = input("Enter another noun: ")
        adjective_three = input("Enter another adjective: ")
        verb_one = input("Enter a verb ending in -ed: ")
        plural_noun_one = input("Enter a plural noun: ")
        adjective_four = input("Enter another adjective: ")
        adverb_one = input("Enter an adverb: ")
        feeling_two = input("Enter another feeling: ")
        noun_three = input("Enter another noun: ")
        noun_four = input("Enter another noun: ")
        feeling_three = input("Enter another feeling: ")
        number_one = input("Enter a random number: ")
        adjective_five = input("Enter another adjective: ")
        feeling_four = input("Enter another feeling: ")
        verb_two = input("Enter a verb in the present tense: ")
     """
