""" STORY ONE
        adjective_one = input("Enter an adjective: ")
        feeling_one = input("Enter a feeling: ")
        noun_one = input("Enter a noun: ")
        place_one = input("Enter a place: ")
        adjective_two = input("Enter another adjective: ")
        animal_one = input("Enter a type of animal: ")
        noun_two = input("Enter another noun: ")
        adjective_three = input("Enter another adjective: ")
        verb_one = input("Enter a verb ending in -ed: ")
        plural_noun_one = input("Enter a plural noun: ")
        adjective_four = input("Enter another adjective: ")
        adverb_one = input("Enter an adverb: ")
        feeling_two = input("Enter another feeling: ")
        noun_three = input("Enter another noun: ")
        noun_four = input("Enter another noun: ")
        feeling_three = input("Enter another feeling: ")
        number_one = input("Enter a random number: ")
        adjective_five = input("Enter another adjective: ")
        feeling_four = input("Enter another feeling: ")
        verb_two = input("Enter a verb in the present tense: ")

    STORY TWO
         adjective_one = input("Enter an adjective: ")
        noun_one = input("Enter a noun: ")
        verb_one = input("Enter a verb ending in -ing: ")
        verb_two = input("Enter another verb: ")
        place_one = input("Enter a place: ")
        adjective_two = input("Enter another adjective: ")
        noun_two = input("Enter another noun: ")
        verb_three = input("Enter another verb: ")
        adjective_three = input("Enter another adjective: ")
        noun_three = input("Enter another noun: ")
        exclamation = input("Enter an exclamation, e.g. 'OMG!' or 'Wow!' or 'Oh no!': ")
        adjective_four = input("Enter another adjective: ")
        verb_four = input("Enter a verb in the past tense: ")
        verb_five = input("Enter another verb ending in -ing: ")
        adverb_one = input("Enter an adverb: ")
        noun_four = input("Enter another noun: ")
        verb_six = input("Enter another verb in the past tense: ")
        random_date = input("Enter a random date, e.g. 1995: ")
        any_number = input("Enter a random number: ")

    STORY THREE

        feeling_one = input("Enter a feeling: ")
        city_one = input("Enter the name of a city: ")
        noun_one = input("Enter a noun: ")
        noun_two = input("Enter another noun: ")
        adjective_one = input("Enter an adjective: ")
        feeling_two = input("Enter a feeling: ")
        verb_one = input("Enter a verb ending in -ing: ")
        noun_three = input("Enter a noun: ")
        verb_two = input("Enter another verb: ")
        any_number = input("Enter a random number: ")
        adjective_two = input("Enter another adjective: ")
        city_two = input("Enter another name of a city: ")
        adverb_one = input("Enter an adverb: ")
        adjective_three = input("Enter another adjective: ")
        noun_four = input("Enter another noun: ")
        adjective_four = input("Enter another adjective: ")
        plural_noun_one = input("Enter a plural noun: ")
        feeling_three = input("Enter another feeling: ")
        noun_three = input("Enter another noun: ")
        clothing_plural = input("Enter an item of clothing (plural): ")

    STORY FOUR 
        season_one = input("Enter a season: ")
        adjective_one = input("Enter an adjective: ")
        country = input("Enter the name of a country: ")
        adjective_two = input("Enter another adjective: ")
        feeling_one = input("Enter a feeling: ")
        clothing = input("Enter an item of clothing: ")
        adjective_three = input("Enter another adjective: ")
        adverb_one = input("Enter an adverb: ")
        noun_one = input("Enter a noun: ")
        plural_noun_one = input("Enter a plural noun: ")
        adjective_four = input("Enter another adjective: ")
        adverb_one = input("Enter an adverb: ")
        noun_three = input("Enter another noun: ")
        feeling_two = input("Enter another feeling: ")
        place_one = input("Enter a place: ")
        exclamation_one = input("Enter an exclamation, e.g. 'OMG!': ")
        adjective_five = input("Enter another adjective: ")
        verb_one = input("Enter a verb ending in -ing: ")
        verb_two = input("Enter another verb ending in -ing: ")
        noun_four = input("Enter another noun: ")

    STORY FIVE 
        adjective_one = input("Enter an adjective: ")
        noun_one = input("Enter a noun: ")
        verb_one = input("Enter a verb ending in -ing: ")
        feeling_one = input("Enter a feeling: ")
        adjective_two = input("Enter an adjective: ")
        adjective_three = input("Enter another adjective: ")
        adverb_one = input("Enter an adverb: ")
        adverb_two = input("Enter another adverb: ")
        clothing_one = input("Enter an item of clothing: ")
        noun_two = input("Enter another noun: ")
        adjective_four = input("Enter another adjective: ")
        clothing_two = input("Enter another item of clothing: ")
        verb_two = input("Enter another verb ending in -ing: ")
        body_part = input("Enter a body part: ")
        feeling_one = input("Enter a feeling: ")
        noun_two = input("Enter another noun: ")
        noun_three = input("Enter another noun: ")
        verb_three = input("Enter another verb ending in -ing: ")
        feeling_two = input("Enter another feeling: ")

    STORY SIX
        adjective_one = input("Enter an adjective: ")
        type_of_holiday = input("Enter a type of holiday, e.g. Christmas: ")
        adjective_two = input("Enter another adjective: ")
        plural_noun_one = input("Enter a plural noun: ")
        noun_two = input("Enter another noun: ")
        plural_noun_two = input("Enter another plural noun: ")
        adjective_three = input("Enter another adjective: ")
        verb_one = input("Enter a verb: ")
        adjective_four = input("Enter another adjective: ")
        verb_two = input("Enter a verb ending in -ing: ")
        body_part = input("Enter a body part: ")
        noun_four = input("Enter another noun: ")
        place_one = input("Enter a place: ")
        adjective_five = input("Enter another adjective: ")
        noun_five = input("Enter another noun: ")
        adverb_one = input("Enter an adverb: ")
        adjective_six = input("Enter another adjective: ")
        noun_six = input("Enter another noun: ")
        animal_one = input("Enter a type of animal: ")
        verb_three = input("Enter another verb: ")
        adverb_two = input("Enter another adverb: ")
        number = input("Enter a random number: ")

    STORY SEVEN 

    feeling_one = input("Enter a feeling: ")
        adjective_one = input("Enter an adjective: ")
        adverb_one = input("Enter an adverb: ")
        noun_one = input("Enter a noun: ")
        adjective_two = input("Enter another adjective: ")
        plural_noun_one = input("Enter a plural noun: ")
        verb_one = input("Enter a verb ending in -ing: ")
        verb_two = input("Enter another verb ending in -ing: ")
        verb_three = input("Enter another verb ending in -ing: ")
        noun_three = input("Enter another noun: ")
        adjective_three = input("Enter another adjective: ")
        place = input("Enter a place: ")
        plural_noun_two = input("Enter another plural noun: ")
        plural_noun_three = input("Enter another plural noun: ")
        verb_four = input("Enter another verb ending in -ing: ")
        name = input("Enter the name of someone you know: ")
        superhero = input("Enter the name of your favourite superhero: ")
        plural_noun_four = input("Enter another plural noun: ")
        plural_noun_five = input("Enter another plural noun: ")
        adjective_four = input("Enter another adjective: ")

    STORY EIGHT

        adjective_one = input("Enter an adjective: ")
        body_part = input("Enter the name of a body part: ")
        adjective_two = input("Enter another adjective: ")
        adjective_three = input("Enter another adjective: ")
        plural_noun_one = input("Enter a plural noun: ")
        verb_one = input("Enter a verb ending in -ing: ")
        verb_two = input("Enter another verb ending in -ing: ")
        adjective_four = input("Enter another adjective: ")
        noun_one = input("Enter a noun: ")
        adverb_one = input("Enter an adverb: ")
        verb_three = input("Enter another verb ending in -ing: ")
        adjective_five = input("Enter another adjective: ")
        colour = input("Enter a colour: ")
        clothing_plural = input("Enter an item of clothing(plural): ")
        number = input("Enter a random number: ")
        plural_noun_two = input("Enter another plural noun: ")
        adverb_two = input("Enter another adverb: ")
        verb_four = input("Enter another verb ending in -ing: ")
        adjective_six = input("Enter another adjective: ")
        plural_noun_three = input("Enter another plural noun: ")
        verb_five = input("Enter another verb ending in -ing: ")
     """

